version: 1

formatters:
  default:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

handlers:
  main:
    class: logging.handlers.RotatingFileHandler
    filename: /home/ubuntu/streamlineai/backend/logs/main.log
    formatter: default
    level: INFO
    maxBytes: 10485760  # 10 MB
    backupCount: 5      # keep 5 old logs

  webhook:
    class: logging.handlers.RotatingFileHandler
    filename: /home/ubuntu/streamlineai/backend/logs/webhook.log
    formatter: default
    level: INFO
    maxBytes: 10485760  # 10 MB
    backupCount: 5      # keep 5 old logs

  error:
    class: logging.handlers.RotatingFileHandler
    filename: /home/ubuntu/streamlineai/backend/logs/error.log
    formatter: default
    level: ERROR
    maxBytes: 10485760  # 10 MB
    backupCount: 5      # keep 5 old logs

  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO

loggers:
  __main__:
    level: INFO
    handlers: [main]
    propagate: no

  streamlineai:
    level: INFO
    handlers: [main]
    propagate: no

  webhook:
    level: INFO
    handlers: [webhook]
    propagate: no

  uvicorn:
    level: INFO
    handlers: [main]
    propagate: no

  uvicorn.error:
    level: ERROR
    handlers: [error]
    propagate: no

  uvicorn.access:
    level: INFO
    handlers: [main]
    propagate: no

  fastapi:
    level: INFO
    handlers: [main]
    propagate: no

root:
  level: INFO
  handlers: [main, error]
